INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: true
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: false
GROUP_BY_INCIDENCE_SIGNATURE: true
USE_SIMUL_INTEGERIZER: true
USE_CVXPY: false
max_expansion_factor: 30
geographies:
- REGION
- PUMA
- TRACT
- BLKGRP
seed_geography: PUMA
trace_geography:
  BLKGRP: 261251620002
  TRACT: 26125162000
data_dir: data/2018
input_table_list:
- tablename: households
  filename: SEMCOG_2018_seed_households.csv
  index_col: hh_id
  column_map:
    hhnum: hh_id
- tablename: persons
  filename: SEMCOG_2018_seed_persons.csv
  column_map:
    hhnum: hh_id
    SPORDER: per_num
  drop_columns: null
- tablename: geo_cross_walk
  filename: SEMCOG_2018_geo_cross_walk.csv
  column_map:
    BLKGRPID: BLKGRP
    TRACTID: TRACT
    PUMAID: PUMA
- tablename: BLKGRP_control_data
  filename: SEMCOG_2018_control_totals_blkgrp.csv
  column_map:
    BLKGRPID: BLKGRP
    TRACTID: TRACT
    PUMAID: PUMA
- tablename: TRACT_control_data
  filename: SEMCOG_2018_control_totals_tract.csv
  column_map:
    BLKGRPID: BLKGRP
    TRACTID: TRACT
    PUMAID: PUMA
household_weight_col: WGTP
household_id_col: hh_id
total_hh_control: num_hh
control_file_name: SEMCOG_2018_controls.csv
output_tables:
  action: include
  tables:
  - summary_TRACT
  - summary_BLKGRP
output_synthetic_population:
  household_id: household_id
  households:
    filename: synthetic_households.csv
    columns:
    - BLD
    - YBL
    - TEN
    - hh_id
  persons:
    filename: synthetic_persons.csv
    columns:
    - hh_id
    - per_num
    - AGEP
    - SEX
    - RAC1P
run_list:
  steps:
  - input_pre_processor
  - setup_data_structures
  - initial_seed_balancing
  - meta_control_factoring
  - final_seed_balancing
  - integerize_final_seed_weights
  - sub_balancing.geography=TRACT
  - sub_balancing.geography=BLKGRP
  - expand_households
  - summarize
  - write_tables
  - write_synthetic_population
